import logging
from typing import Any, Dict, Optional

_ZONED_TIMESTAMP_KEY: str = "zoned_timestamp"
_ZONED_TIMESTAMP_UTC_EPOCH_MS_KEY: str = "utc_epoch_ms"
_ZONED_TIMESTAMP_TZ_KEY: str = "timezone"

_LEVEL_KEY: str = "level"
_LEVEL_NO_KEY: str = "no"
_LEVEL_NAME_KEY: str = "name"

_SOURCE_CONTEXT_KEY: str = "source_context"
_SOURCE_CONTEXT_PATH_KEY: str = "path"
_SOURCE_CONTEXT_LINE_KEY: str = "line"

_LOGLIB_GENERATED_MSG_KEY: str = "loglib_generated_msg"


class AutoGeneratedKeyValuePairsBuffer:
    """
    A reusable buffer for creating auto-generated key-value pairs for log
    events.

    This buffer maintains a predefined dictionary structure for common metadata
    fields, allowing efficient reuse without creating new dictionaries for each
    log event.
    """

    def __init__(self) -> None:
        self._buf: Dict[str, Any] = {
            _ZONED_TIMESTAMP_KEY: {
                _ZONED_TIMESTAMP_UTC_EPOCH_MS_KEY: None,
                _ZONED_TIMESTAMP_TZ_KEY: None,
            },
            _LEVEL_KEY: {
                _LEVEL_NO_KEY: None,
                _LEVEL_NAME_KEY: None,
            },
            _SOURCE_CONTEXT_KEY: {
                _SOURCE_CONTEXT_PATH_KEY: None,
                _SOURCE_CONTEXT_LINE_KEY: None,
            },
        }

    def generate(
        self, timestamp: int, timezone: Optional[str], record: logging.LogRecord
    ) -> Dict[str, Any]:
        """
        Generated auto-generated key-value pairs by populating the underlying
        buffer with the given log event metadata.

        :param timestamp: The Unix epoch timestamp in millisecond of the log
            event.
        :param timezone: The timezone of the log event, or None if not
            applicable.
        :param record: The LogRecord containing metadata for the log event.
        :return: The populated underlying buffer as the auto-generated key-value
            pairs.
        """

        self._buf[_ZONED_TIMESTAMP_KEY][_ZONED_TIMESTAMP_UTC_EPOCH_MS_KEY] = timestamp
        self._buf[_ZONED_TIMESTAMP_KEY][_ZONED_TIMESTAMP_TZ_KEY] = timezone

        # NOTE: we don't serialize all the metadata given by `record`. Currently, we only add the
        # following metadata into auto-generated kv pairs:
        # - log level
        # - source context

        self._buf[_LEVEL_KEY][_LEVEL_NO_KEY] = record.levelno
        self._buf[_LEVEL_KEY][_LEVEL_NAME_KEY] = record.levelname

        self._buf[_SOURCE_CONTEXT_KEY][_SOURCE_CONTEXT_PATH_KEY] = record.pathname
        self._buf[_SOURCE_CONTEXT_KEY][_SOURCE_CONTEXT_LINE_KEY] = record.lineno

        return self._buf


def create_loglib_generated_log_event(
    timestamp: int, timezone: Optional[str], msg: str
) -> Dict[str, Any]:
    """
    :param timestamp: The Unix epoch timestamp in millisecond of the log event.
    :param timezone: The timezone of the log event, or None if not applicable.
    :param msg: The log message generated by the logging library.
    :return: The auto-generated key-value pairs that represents a log event generated by the logging
        library itself.
    """
    return {
        _ZONED_TIMESTAMP_KEY: {
            _ZONED_TIMESTAMP_UTC_EPOCH_MS_KEY: timestamp,
            _ZONED_TIMESTAMP_TZ_KEY: timezone,
        },
        _LOGLIB_GENERATED_MSG_KEY: msg,
    }
