name: Python package

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.6", "3.8", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,test]

      - name: docformatter
        run: docformatter --check --diff src tests

      - name: black
        run: black --diff --check src/ tests/

      - name: ruff
        run: ruff check --format=github src/ tests/

      - name: mypy
        run: mypy src/ tests/

      - name: Test
        run: python -m unittest -bv

      - name: Build
        run: python -m build
