name: Lint, build, and test package

on:
  pull_request:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          python -m pip install --upgrade pip
          pip install .[dev,test]

      - run: docformatter --check --diff src tests

      - run: black --diff --check src/ tests/

      - run: ruff check --format=github src/ tests/

      - run: mypy src/ tests/

      - run: python -m build

      - uses: actions/upload-artifact@v3
        with:
          name: wheel-${{ matrix.python-version }}
          path: dist/*
          retention-days: 1

  test:
    needs: [build]
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.8", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v3
        with:
          name: wheel-${{ matrix.python-version }}
          path: dist/

      - run: |
          python -m pip install --upgrade pip
          pip install dist/clp_logging-*.whl
          pip install -r requirements-test.txt

      - name: Run unit tests (all)
        if: ${{ 'macos-latest' != matrix.os }}
        run: python -m unittest -fv

      - name: Run unit tests (skip log level timeout)
        if: ${{ 'macos-latest' == matrix.os }}
        run: >
            python -m unittest -fv
            tests.test_handlers.TestCLPSock_ZSTD
            tests.test_handlers.TestCLPSock_RAW
            tests.test_handlers.TestCLPStream_ZSTD
            tests.test_handlers.TestCLPStream_RAW
            tests.test_handlers.TestCLPSegmentStreaming_ZSTD
            tests.test_handlers.TestCLPSegmentStreaming_RAW

  test-py36:
    needs: [build]
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.6"

      - uses: actions/download-artifact@v3
        with:
          name: wheel-3.8
          path: dist/

      - run: |
          python -m pip install --upgrade pip
          pip install dist/clp_logging-*.whl
          pip install -r requirements-test.txt

      - name: Run unit tests (all)
        if: ${{ 'macos-latest' != matrix.os }}
        run: python -m unittest -fv

      - name: Run unit tests (skip log level timeout)
        if: ${{ 'macos-latest' == matrix.os }}
        run: >
            python -m unittest -fv
            tests.test_handlers.TestCLPSock_ZSTD
            tests.test_handlers.TestCLPSock_RAW
            tests.test_handlers.TestCLPStream_ZSTD
            tests.test_handlers.TestCLPStream_RAW
            tests.test_handlers.TestCLPSegmentStreaming_ZSTD
            tests.test_handlers.TestCLPSegmentStreaming_RAW
