name: Upload package to pypi

on:
  push:
    tags:
      - v*

jobs:
  package:
    uses: ./.github/workflows/package.yaml
  # https://docs.pypi.org/trusted-publishers/using-a-publisher/
  pypi-publish:
    needs: [package]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - uses: actions/download-artifact@v3
        with:
          name: wheel-3.8
          path: dist/

      - if: ${{ github.repository_owner != 'y-scope' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - if: ${{ github.repository_owner == 'y-scope' }}
        uses: pypa/gh-action-pypi-publish@release/v1
